# config.yaml

#We include a metadata file for sample identification which includes where the sample data is stored
metadata_file: example_data/metadata/example_metadata.csv

#Below the output directory is specified (outputs of the workflow will be stored here)
output_dir: example_data/example_output

#Adapter parameters
adapter_dir: adapters/adapters.fa
trim_left: 20
trim_right: 140
kmer_length: 20

#We indicate where the databases are stored 
database_dir: ref_databases
hostile_dir:  ref_databases/hostile/human-t2t-hla-argos985 
kraken_db_loc: ref_databases/kraken
chocoplhan_db_loc: ref_databases/humann/chocophlan
uniref_db_loc: ref_databases/humann/uniref
utility_mapping_db_loc: ref_databases/humann/utility_mapping


#Bracken parameters
bracken_read_len: 100
bracken_kmer_len: 35
